debug: true

server:
  servlet:
    context-path: /
  port: 8085
  
spring:
  application:
    name: data-service
  activemq:
   broker-url: tcp://localhost:61616
  datasource:
    jdbcUrl: jdbc:oracle:thin:@srvdpxodb03a.tokiomarine.com.br:1527:acim
    url: jdbc:oracle:thin:@srvdpxodb03a.tokiomarine.com.br:1527:acim
    #username: ADMACI
    username: ADMACI 
    password: Tokio123
    driverClassName: oracle.jdbc.OracleDriver   
  hikari:
    connectionTimeout: 30000
    maximumPoolSize: 250
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate.globally_quoted_identifiers: true
    hibernate.current_session_context_class: thread
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        current_session_context_class: thread
        ddl-auto: none
        javax:
         cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
           use_second_level_cache: false
           use_query_cache: false
           region:
              factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  ehcache:
      config: classpath:ehcache.xml                  
  properties:
    javax:
      persistence:
        sharedCache: 
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
        mode: ENABLE_SELECTIVE 
  cloud:
     config:
       enabled: false            
     
management:
   endpoints:
      web:
         base-path: /actuator
         exposure:
            include: "*"

eureka:
  instance:
    hostname: localhost
    eureka-server-port: 8088
    non-secure-port: 8085
    non-secure-port-enabled: true
    instanceId: ${spring.application.name}:${random.value}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.eureka-server-port}/eureka-server/eureka
                     